### ISSUE TITLE
Accessing Nexus repository manager password in a kubernetes pod

### ISSUE THREAD

**Issue by saurav28** [sonatype/helm3-charts#100]
I have installed Sonatype nexus repository manager in my Kubernetes Cluster using the helm chart,

I am using Kyma installation.

Nexus repository manager got installed properly and i can access the application.

But it seems the login password file is in a pv volume claim /nexus-data attached in the pod.

Now whenever i am trying to access the pod with kubectl exec command

kubectl exec -i -t $POD_NAME -n dev -- /bin/sh
I am getting the following error

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
I understand that this issue is because of the image does not offer shell functionality. Is there any other way i can access the password file present in the pvc ?

**Comment by jflinchbaugh** [comment]
Are you using the image from docker hub that's the default in the chart? It should allow "/bin/sh" or "bash" to execute like you tried.
Alternatively, you could try to cat out the password directly:
```$ kubectl exec -it $POD_NAME -n dev -- cat  /nexus-data/admin.password```

**Comment by saurav28** [comment]
@jflinchbaugh thanks for the reply...even the cat command fails with this
container_linux.go:367: starting container process caused: exec: "echo": executable file not found in $PATH: unknown

i have used the default values only
