### ISSUE TITLE
Image pull secrets not working as aspected

### ISSUE THREAD

**Issue by ChristianSpiess** [sonatype/helm3-charts#105]
https://github.com/sonatype/helm3-charts/blob/777489d20b006a588c99f26d4ef51a817450ed57/charts/nexus-repository-manager/templates/deployment.yaml#L51

```     {{- if .Values.nexus.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

should be something like :
```      {{- if .Values.nexus.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml  .Values.nexus.imagePullSecrets  | nindent 8 }}
      {{- end }}
```

or :

```      {{- if .Values.nexus.imagePullSecrets }}
      imagePullSecrets:
        {{- with ..Values.nexus.imagePullSecrets }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
```

The imagePullSecret value inside https://github.com/sonatype/helm3-charts/blob/777489d20b006a588c99f26d4ef51a817450ed57/charts/nexus-repository-manager/values.yaml#L70
in on the main layer and not in the nexus chapter (but should be on nexus layer).

**Comment by icy95** [comment]
Hi! Any updates on this ?

**Comment by jflinchbaugh** [comment]
This has been fixed. imagePullSecrets on the NXRM chart should now work as described:
https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager#using-the-image-from-the-red-hat-registry
