### ISSUE TITLE
Nexus Behind Reverse Proxy Nginx

### ISSUE THREAD

**Issue by mhhhkay** [sonatype/helm3-charts#108]
Hey Folks,
I've tried to follow this guide https://help.sonatype.com/repomanager3/installation/run-behind-a-reverse-proxy (and others) to access my nexus3 container.
However if I try to access it, I just see broken links as files can't be found.
I assume my nginx config is not working properly but I don't know which wheel needs to be turned here.
Is there anything special to be thought of with nexus in particular? Any basepath to be adjusted?

All hints highly appreciated.

My current nginx config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: confnginx
data:
  nginx.conf: |

    upstream nexus-upstream {
      server nexus:8081;
    }
    server {
       listen 80;
       location /nexus/ {
       rewrite ^/nexus(.*) $1 break;
       proxy_pass http://nexus-upstream;
       proxy_set_header Host $host:$server_port;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        }
```
My outcome within any browser:

![image](https://user-images.githubusercontent.com/89981500/131844099-cc876ea7-d70c-4661-a7e5-5ff3f8fc7ae5.png)

Logs of the nginx which shows that required CSS files cant be found/accessed:

`192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /nexus/ HTTP/1.1" 200 8810 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *1 open() "/etc/nginx/html/static/rapture/resources/loading-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/loading-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/loading-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *1 open() "/etc/nginx/html/static/rapture/resources/nexus-proui-plugin-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/nexus-proui-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/nexus-proui-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/nexus-proui-bundle.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *3 open() "/etc/nginx/html/static/nexus-proui-bundle.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/nexus-proui-bundle.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
2021/09/02 12:32:42 [error] 23#23: *5 open() "/etc/nginx/html/static/rapture/resources/baseapp-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/baseapp-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/baseapp-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *4 open() "/etc/nginx/html/static/rapture/resources/nexus-rapture-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/nexus-rapture-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/nexus-rapture-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *7 open() "/etc/nginx/html/static/rapture/resources/nexus-coreui-plugin-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/nexus-coreui-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/nexus-coreui-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *6 open() "/etc/nginx/html/static/rapture/resources/nexus-proximanova-plugin-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/nexus-proximanova-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/nexus-proximanova-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/resources/nexus-onboarding-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *1 open() "/etc/nginx/html/static/rapture/resources/nexus-onboarding-plugin-prod.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/resources/nexus-onboarding-plugin-prod.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
2021/09/02 12:32:42 [error] 23#23: *3 open() "/etc/nginx/html/static/nexus-rapture-bundle.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/nexus-rapture-bundle.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/nexus-rapture-bundle.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/nexus-coreui-bundle.css?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *5 open() "/etc/nginx/html/static/nexus-coreui-bundle.css" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/nexus-coreui-bundle.css?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
2021/09/02 12:32:42 [error] 23#23: *3 open() "/etc/nginx/html/static/rapture/baseapp-prod.js" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/baseapp-prod.js?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/baseapp-prod.js?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *5 open() "/etc/nginx/html/static/rapture/extdirect-prod.js" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/extdirect-prod.js?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/rapture/extdirect-prod.js?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *1 open() "/etc/nginx/html/static/nexus-coreui-bundle.js" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/nexus-coreui-bundle.js?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
192.168.1.50 - - [02/Sep/2021:12:32:42 +0000] "GET /static/nexus-coreui-bundle.js?_v=3.33.1-01&_e=OSS HTTP/1.1" 404 555 "http://192.168.1.51/nexus/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
2021/09/02 12:32:42 [error] 23#23: *6 open() "/etc/nginx/html/static/rapture/bootstrap.js" failed (2: No such file or directory), client: 192.168.1.50, server: , request: "GET /static/rapture/bootstrap.js?_v=3.33.1-01&_e=OSS HTTP/1.1", host: "192.168.1.51", referrer: "http://192.168.1.51/nexus/"
`

**Comment by ruckc** [comment]
With nexus and nginx, just use the ingrss-nginx ingress controller.  It does all the work automatically

**Comment by mhhhkay** [comment]
unfortunately we have no ingress controller running and use a standalone nginx as of now.

**Comment by jflinchbaugh** [comment]
closing as this issue has gone stale and is more about nginx config.
