### ISSUE TITLE
several suggestions

### ISSUE THREAD

**Issue by Hokwang** [sonatype/helm3-charts#11]
Hi,

First of all, I am really looking forward providing helm chart officially. Now it is.

But I think this is early stage of chart.

1. when I use `statefulset.enabled: true` this chart does not work.
and I want to know nexus support (need)  statefulset or not really.

2. config does not support now.
please refer to https://github.com/Oteemo/charts/blob/8f81bbda4913893fddeec7e6f9c033ce32e2a0a6/charts/sonatype-nexus/values.yaml#L207-L210
Or how to use secret than configmap when I use for create file?
```
data:
  keycloak.json: |
    {
      "realm": "test",
      "auth-server-url": "https://company.net/keycloak/",
      "ssl-required": "external",
      "resource": "nexus",
      "credentials": {
        "secret": "blah"
      },
      "confidential-port": 0
    }
```

3. someone can not use docker repo. so I think ingress.yaml needs below
```
{{ if .Values.ingress.hostDocker }}
  - host: <snip>
{{ end }}
```

Thanks,

**Comment by CMYanko** [comment]
Thanks for the feedback! 

Wrt #1, I have taken close look and I don't think a stateful set is needed, I thought I even took away to value / option to enable it.

#2 - Config is a case of I didn't understand the use case but have been digging into it the last couple of days and now I better understand it and will re-implement the option. What I'll need is a simple example I can use in my testing.

I don't fully understand #3 yet but that gives me something to go on

**Comment by Hokwang** [comment]
Thanks for reply.
item 1, refer to jenkins's helm chart, (I think that is same java base tool) there's no statefulset config and 
https://github.com/jenkinsci/helm-charts/blob/f251fce11b8c7dd376059732d965112e505907a3/charts/jenkins/templates/jenkins-master-deployment.yaml#L25-L26
there's strategy type is automatically selected. Please consider this.

item 2, I am using https://github.com/flytreeleft/nexus3-keycloak-plugin this plugin. and this needs to save some file in pv.

item 3, I want to use nexus for npm, binary, etc 's repo except docker. because I have other tool for it.
so my values.yaml is 
```
ingress:
  enabled: true
  hostDocker: ""
```
but this create rules like
```
  rules:
    - host: 
      http:
        paths:
          - path: 
            backend:
              serviceName: nexus-stage-nexus-repository-manager
              servicePort: 5000
```

**Comment by CMYanko** [comment]
Got it! I will work on 2 & 3 today. For docker I'll add the logic but I think you also need to override the dockerPort, I'll add the logic to both of those

**Comment by CMYanko** [comment]
Ok, I've published an updated chart with support for 2 & 3

**Comment by Hokwang** [comment]
two more thing I found.
item 4:
https://github.com/sonatype/helm3-charts/blob/1afee5585f039cd610041267fbf362004a10b466/nexus-repository-manager/values.yaml#L13
https://github.com/sonatype/helm3-charts/blob/1afee5585f039cd610041267fbf362004a10b466/nexus-repository-manager/values.yaml#L62

there's imagepullsecret is duplicated.

item 5:
I think `tolerations:` should be moved to bottom of `nexus.nodeSelector:` or vise versa.

https://github.com/sonatype/helm3-charts/blob/1afee5585f039cd610041267fbf362004a10b466/nexus-repository-manager/values.yaml#L157

Thanks,

**Comment by Hokwang** [comment]
now I tested your updated chart. there's error.
https://github.com/sonatype/helm3-charts/blob/1afee5585f039cd610041267fbf362004a10b466/nexus-repository-manager/templates/configmap.yaml#L6-L10

please check indentation. below is error message.
```
coalesce.go:199: warning: destination for data is a table. Ignoring non-table value []
Error: YAML parse error on nexus-repository-manager/templates/configmap.yaml: error converting YAML to JSON: yaml: line 6: did not find expected key
```

**Comment by CMYanko** [comment]
Removed duplicate ImagePullSecret

**Comment by CMYanko** [comment]
I don't understand the issue with Tolerations, it's a top level value.

How did you test the labels? I don't see an indentation issue and the error sounds like an empty map was passed in??

**Comment by Hokwang** [comment]
@CMYanko 
item 5 : Yes, that's true, that's just my opinion and `tolerations` position is usally close to `nodeSelector`.

**Comment by CMYanko** [comment]
I made some recent fixes to the configmap, there was a name missmatch pointed out in a separate issue

**Comment by Hokwang** [comment]
@CMYanko any updates?

**Comment by CMYanko** [comment]
Updates have been applied, nothing on stateful set though

**Comment by Hokwang** [comment]
@CMYanko you said "Removed duplicate ImagePullSecret" but I can't find.
And item 6 when using `config.enable: true` parse error still exist.
maybe you have changes in your local repo.

**Comment by CMYanko** [comment]
You're right, I just pushed up 27.0.3 and 38.0.0.

let me look into the config.enabled now

**Comment by CMYanko** [comment]
fixed the parser error too 28.0.1

**Comment by Hokwang** [comment]
@CMYanko Many thanks

**Comment by joedragons** [comment]
@Revanthchowdary9 Keycloak (SAML) is a Pro (licensed) feature in Nexus Repository (3).  If you are licensed, you should contact support for assistance.  If you're having problems with a third party plugin, this is not supported by Sonatype so this is not the right place to ask.  For official SAML page see https://help.sonatype.com/display/NXRM3/SAML.
