### ISSUE TITLE
Helm Repository not working

### ISSUE THREAD

**Issue by dajudge** [sonatype/helm3-charts#110]
I followed the instructions provided at https://github.com/sonatype/helm3-charts/blob/main/docs/index.md

Adding the helm repository does not work:

```
$ helm repo add sonatype https://sonatype.github.io/helm3-charts/
Error: looks like "https://sonatype.github.io/helm3-charts/" is not a valid chart repository or cannot be reached: failed to fetch https://sonatype.github.io/helm3-charts/index.yaml : 404 Not Found
```

Here's my helm version:
```
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

**Comment by lfvjimisola** [comment]
Can confirm this from command line as well as with ArgoCD.

**Comment by jaredhanson11** [comment]
+1, looks like the chart repo was moved or something broke.

Additional info/note - 2 days ago was the last time I can confirm that it was working so timeframe of 404's were sometime within the past 2 days

**Comment by ruckc** [comment]
normally the github.io urls are based on a gh-pages branch, which is no longer present in the repository.

**Comment by lfvjimisola** [comment]
works for us again now

**Comment by dajudge** [comment]
Can confirm it's working again.

**Comment by jflinchbaugh** [comment]
We offer our apologies for the repo disappearing for a bit. It seems renaming the "master" branch to "main" may have caused a disruption serving the "/docs" directory as our github pages. As you've seen, it's been corrected.
