### ISSUE TITLE
Configmap name mismatch

### ISSUE THREAD

**Issue by sighup** [sonatype/helm3-charts#12]
iqserver.fullname is used for the configmap in the deployment:

https://github.com/sonatype/helm3-charts/blob/ea924ce8e710c4ec5340ed2f92979e24e5461778/nexus-iq/templates/deployment.yaml#L67-L69

But it is generated as iqserver.fullname-conf

https://github.com/sonatype/helm3-charts/blob/ea924ce8e710c4ec5340ed2f92979e24e5461778/nexus-iq/templates/configmap.yaml#L4

Causing: MountVolume.SetUp failed for volume "config-volume" : configmap "nexus-iq-nexus-iq-server" not found

In my case the configmap was installed to nexus-iq-nexus-iq-server-conf which did not equal nexus-iq-nexus-iq-server and caused the error above.

**Comment by CMYanko** [comment]
Thanks, I've just made the change and will look to publish an updated chart today

**Comment by daniel-oh** [comment]
Running into the same issue as sighup above ^. Thanks for lookingi nto this @CMYanko

**Comment by CMYanko** [comment]
Ok, we just released 99 so I've built the new chart with the configmap fix in place

**Comment by daniel-oh** [comment]
Thanks @CMYanko and @sighup . The config-map issue is fixed - running into a separate error with failing liveness/readiness probes now - will troubleshoot and possibly open a separate issue

**Comment by CMYanko** [comment]
Great, I'll close this, thanks again.
