### ISSUE TITLE
27.0.2 not mounting nexus-data PVC

### ISSUE THREAD

**Issue by pineman** [sonatype/helm3-charts#13]
Hi,

I've noticed this commit https://github.com/sonatype/helm3-charts/commit/2175409be5ae0e129774fae6e53de161bcefdf6e#diff-bfac4247543c05f946d981c211baba2dL106 (in the most recent chart version 27.0.2) disables the PVC mount. Is this intended? I noticed that my nexus pod's config does not survive e.g., deletions of the pod. When it starts back up, its like a clean install and the PVC always says (with `kubectl describe`) its not mounted.

**Comment by CMYanko** [comment]
Oh boy, let me look. time to fire minikube back up!

**Comment by CMYanko** [comment]
Good catch, thanks! I just pushed up 27.0.3 and will shortly add 3.28

**Comment by pineman** [comment]
@CMYanko Thanks!
