### ISSUE TITLE
nexus - volume error

### ISSUE THREAD

**Issue by Hokwang** [sonatype/helm3-charts#14]
Hi,

There's several volume issues.

item 1:
Recently `volumeMounts:` is newly added.
https://github.com/sonatype/helm3-charts/blob/592c736470b95b745d1485d280100e12c2b6d316/nexus-repository-manager/templates/deployment.yaml#L107-L111

But there's no `volumes:` 
so here's error.
```
coalesce.go:199: warning: destination for data is a table. Ignoring non-table value []
Error: Deployment.apps "nexus-stage-nexus-repository-manager" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "nexus-stage-nexus-repository-manager-data", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "nexus-stage-nexus-repository-manager-backup"]
```

so you need to add (below is example)
```
        - name: {{ template "nexus.fullname" . }}-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (include "nexus.fullname" .) "data") }}
          {{- else }}
          emptyDir: {}
          {{- end }}
```

item 2: And I think you don't support `backup` feature now.
remove 
```
            - mountPath: /nexus-data/backup	
              name: {{ template "nexus.fullname" . }}-backup
```

item 3: config's `volumes` and `volumeMounts` needed
add like
```
          volumeMounts:
            {{- if .Values.config.enabled }}
            - mountPath: {{ .Values.config.mountPath }}
              name: {{ template "nexus.name" . }}-conf
            {{- end }}
```
```
      volumes:
        {{- if .Values.config.enabled }}
        - name: {{ template "nexus.name" . }}-conf
          configMap:
            name: {{ template "nexus.name" . }}-conf
        {{- end }}
```

**Comment by pineman** [comment]
Also seeing this since #13

**Comment by Amos-85** [comment]
same issue when defining `statefulset.enabled=false` & `persistence.enabled=false`

**Comment by Hokwang** [comment]
@CMYanko Please take care.

**Comment by CMYanko** [comment]
Thanks for the feedback, I’ll try and bang this out today

**Comment by CMYanko** [comment]
Ok, pushed up 28.0.2

**Comment by Hokwang** [comment]
@CMYanko 
Still error!

`name` does not match.

https://github.com/sonatype/helm3-charts/blob/f1f549d1fca4c4bae69b198ee1148180f7b60a61/nexus-repository-manager/templates/deployment.yaml#L107-L109

https://github.com/sonatype/helm3-charts/blob/f1f549d1fca4c4bae69b198ee1148180f7b60a61/nexus-repository-manager/templates/deployment.yaml#L129-L131

**Comment by Amos-85** [comment]
Yes @Hokwang 
There is still issue when disabling persistence.

**Comment by CMYanko** [comment]
Doh! names match in 28.0.3, sorry about that. Gotta stop doing latte friday releases ;-)

**Comment by Hokwang** [comment]
@CMYanko 

Again error!!!

https://github.com/sonatype/helm3-charts/blob/ac55544cafb87a4e0f05b6943c68c288785d0d5b/nexus-repository-manager/templates/configmap.yaml#L5

**Comment by CMYanko** [comment]
Crap, my bad. 28.0.4 is up, set everything to 'name' and not 'fullname'

**Comment by Hokwang** [comment]
I don't use secret so now I have no problem,
but what is `Xname`? maybe errata?
https://github.com/sonatype/helm3-charts/blob/40efa61ffedb8f3f83ffebdb6a6b69faab43214a/nexus-repository-manager/templates/deployment.yaml#L116

**Comment by CMYanko** [comment]
I'm not seeing this???

**Comment by Hokwang** [comment]
Long time, many thanks.
