### ISSUE TITLE
Is it possible to set administrator password from secret? 

### ISSUE THREAD

**Issue by mshanmu** [sonatype/helm3-charts#159]
I have set the NEXUS_SECURITY_RANDOMPASSWORD="false" and would like to use secret to set the password. Something like below,

# # To use an additional secret, set enable to true and add data
secret:
  enabled: true
  mountPath: /etc/secret-volume
  readOnly: true
  data: xyz123

Is this possible?

**Comment by jflinchbaugh** [comment]
currently, you must login and change the password from the initial password. there's no way to specify it.
