### ISSUE TITLE
Nexus in High Availability 

### ISSUE THREAD

**Issue by Revanthchowdary9** [sonatype/helm3-charts#164]
Can Any one please help me regarding the Nexus with High availability , When i deployed with 2 replicas getting one pod crashloopBackoff. when i attached pvc .

What is the reason can anyone explian .

**Comment by srini-hdp** [comment]
Nexus does not support running multiple instances with same pvc. 
Please refer below doc
https://help.sonatype.com/repomanager3/planning-your-implementation/resiliency-and-high-availability/single-data-center-on-premises-deployment-example-using-kubernetes
