### ISSUE TITLE
container repository ingress configuration

### ISSUE THREAD

**Issue by ruckc** [sonatype/helm3-charts#17]
It would be nice if the container registry ingress configuration was better documented, we got it working after significant strife in reverse engineering how the template/ingress.yaml was being read.

Also, for cert-manager to generate certificates for both of our nexus and container registry domains, we ended up having to create a separate ingress rule as cert-manager didn't add both ingress.tls.hosts to the secret.  

Separately, what about multiple container repositories?  Can they be collapsed onto the same port or do we need a separate fqdn/certificate/port for each one?

**Comment by CMYanko** [comment]
My expectation is that most folks will implement their own ingress and just use the chart to deploy us as a service. As such I expose the expected ports if docker is enabled but don't set up ingress or certs.

I'm not clear on the ports question. We generally lump docker proxies and a hosted registry all under on 'group'. the group is then the single port for all of those repos to push and pull from. If however, you want multiple hosted (private) registries then each on you want to push to will need it's own port.

**Comment by ruckc** [comment]
to support multiple distinct container registries it will need to be multiple ports.  I'd highly recommend restructuring your ingress configuration anyway because its not just the ingress we have to recreate, its a service for each container registry port.

I would recommend restructuring the chart to deploy a standard service with optional ingress for http/https and just provide us a list to populate for one or more container registries so we can automate the service and ingress without conflicting with the default ingress/service(s).

**Comment by ruckc** [comment]
@CMYanko the #27 PR fixes the previous PR... the deployment ports weren't getting opened properly.

**Comment by ruckc** [comment]
fixed in 23.1.5
