### ISSUE TITLE
Support for External DB

### ISSUE THREAD

**Issue by arnouthoebreckx** [sonatype/helm3-charts#175]
Nexus has support for external databases since 3.31.0 https://help.sonatype.com/repomanager3/planning-your-implementation/sql-database-options

Can this feature be added to the helm-chart?

**Comment by jflinchbaugh** [comment]
external databases are supported in the pro server, and support can help you with it.
database options can be set in the environment via the values.yaml. Modify the INSTALL4J_ADD_VM_PARAMS env variable with your DB connection information:
```
- name: INSTALL4J_ADD_VM_PARAMS
      value: "-Xms2048m -Xmx2048m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs -Dnexus.datastore.enabled=true -Dnexus.datastore.nexus.name=nexus -Dnexus.datastore.nexus.type=jdbc -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://192.168.52.31:5432/nxrm3pg -Dnexus.datastore.nexus.username=nxrm3pg -Dnexus.datastore.nexus.password=nxrm3pg"
```
