### ISSUE TITLE
Nexus RM readiness is never successful

### ISSUE THREAD

**Issue by mattrpav** [sonatype/helm3-charts#176]
1. Stock Nexus Repository Manager v38.0.0 chart (latest)
2. No config changes from stock chart
3. POD restarts due to readiness probe failing
4. Same behavior if service: config is changed from ClusterIP to LoadBalancer

Kuberenetes never sees the 8081 port activate

From within the nexus repository manager pod where the IP is the POD's IP:
```
$ curl http://.. POD IP..:8081/
curl: (7) Failed to connect to ..POD IP port 8081: Connection refused
```

nexus.log does not have any messages that stand out (no ERROR, only INFO and a few minor WARN log entries).  

Most of the WARN messages are related to the karaf etc/ folder being unwritable:
```
org.apache.felix.fileinstall - File is not writeable: file:/opt/sonatype/nexus/etc
```

**Comment by jflinchbaugh** [comment]
Contact support@sonatype.com, and they can help you through installation issues. As this is a stock install, it should work.
