### ISSUE TITLE
Keycloak Integration for Nexus Authentication 

### ISSUE THREAD

**Issue by Revanthchowdary9** [sonatype/helm3-charts#178]
How integrate nexus with keycloak for authentication, can anyone please suggest what are all the steps to do.

as of now i followed this document but unable to get the keycloak login page for nexus UI.

https://github.com/flytreeleft/nexus3-keycloak-plugin

note:- we can directly take this image for keycloak plugin (docker pull kublr/nexus:3.38.0-01)

**Comment by joedragons** [comment]
@Revanthchowdary9 Keycloak (SAML) is a Pro (licensed) feature in Nexus Repository (3). If you are licensed, you should contact support for assistance. If you're having problems with a third party plugin, this is not supported by Sonatype so this is not the right place to ask. For official SAML page see https://help.sonatype.com/display/NXRM3/SAML.
