### ISSUE TITLE
Support for doing initial configuration

### ISSUE THREAD

**Issue by dhs-rec** [sonatype/helm3-charts#179]
Hi,

just tried the Repository Manager chart and wonder how I would do an initial configuration (blob stores, repositories, cleanup policies, etc.) while deploying through helm. Is this possible? If not, consider this a feature request ;-)

**Comment by gbonnefille** [comment]
The Ansible role https://github.com/ansible-ThoTeam/nexus3-oss has a lot of post-configuration features.

**Comment by gbonnefille** [comment]
I also made some post-config only based on the recent API. But I don't imagine how to port this to Helm.

**Comment by jflinchbaugh** [comment]
this is not currently possible from the helm chart.
