### ISSUE TITLE
Add namespace support

### ISSUE THREAD

**Issue by jbod** [sonatype/helm3-charts#18]
Hi!

It would be a nice feature to have the chart (NXRM at least, did not try IQ yet) supporting namespaces, through the `--namespace` option of Helm. It seems that it can only be deployed to the `default` namespace for now.

Maybe i'm not doing things right with this chart, i'm a total beginner with Helm :)

**Comment by Amos-85** [comment]
@jbod,
there is no need to template namespace.
FYI:
[Helm namespace documentation](https://helm.sh/docs/faq/#automatically-creating-namespaces)

**Comment by CMYanko** [comment]
hanks
