### ISSUE TITLE
Suggestions from afar

### ISSUE THREAD

**Issue by rjkernick** [sonatype/helm3-charts#2]
Just wanted to say it is awesome to see you taking over the helm chart. Just a tip for help with the automation of releases: https://github.com/helm/charts-repo-actions-demo.

**Comment by CMYanko** [comment]
Thanks! Looks like something new to learn ;-)

**Comment by CMYanko** [comment]
finally got to this!

**Comment by rjkernick** [comment]
Awesome. Glad it helped!
