### ISSUE TITLE
nexus authentication configuration

### ISSUE THREAD

**Issue by ruckc** [sonatype/helm3-charts#21]
It would be beneficial if the nexus-repository-manager supported configuring saml and/or ldap configuration through the helm chart deployment along with licenses.  Also, what is the supported values for the configmap?  Is it json, yaml, properties?

**Comment by CMYanko** [comment]
I'd think the config map could be used to override the nexus.properties file or the config.yml files

**Comment by CMYanko** [comment]
License can be done with nexus.properties referring to the location of the license file (perhaps a secret?)

**Comment by ruckc** [comment]
any examples of the usage of them?  The documentation for it doesn't exist that I can find
