### ISSUE TITLE
nexus-repository-manager chart removed?

### ISSUE THREAD

**Issue by marijncv** [sonatype/helm3-charts#212]
I was happily experimenting with the nexus-repository-manager helm chart yesterday and was quite surprised to see https://github.com/sonatype/helm3-charts/commit/2bec09c8bfe24c7efe771e0b52eef0d954099dde removing the chart from this repository.

Is there a reason for removing the chart?

**Comment by gigyas** [comment]
It looks like it was moved to here: https://github.com/sonatype/nxrm3-helm-repository
But it would be real cool to have some communication on this

**Comment by bobotimi** [comment]
> I was happily experimenting with the nexus-repository-manager helm chart yesterday and was quite surprised to see [2bec09c](https://github.com/sonatype/helm3-charts/commit/2bec09c8bfe24c7efe771e0b52eef0d954099dde) removing the chart from this repository.
> 
> Is there a reason for removing the chart?

Thank you for your comments @marijncv  and @gigyas . Indeed we have a copy of [this](https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager) Helm chart located in [this](https://github.com/sonatype/nxrm3-helm-repository) repository. However, it  has not yet been officially moved and this is why it is still present [here](https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager) and also the reason why there was no announcement. However, we do appreciate that having this particular Helm chart in two locations causes confusion and as such have removed it from this repository (i.e. [nxrm3-helm-repository](https://github.com/sonatype/nxrm3-helm-repository)). Please continue to use [helm3-charts](https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager).

If there's any such migration in the future, be rest assured that it'll be in just one location and we'll communicate accordingly.

Kind regards
