### ISSUE TITLE
bad notes formatting when ingress is enabled

### ISSUE THREAD

**Issue by jeremypetit-grtgaz** [sonatype/helm3-charts#22]
When ingress is enabled, [NOTES.txt](https://github.com/sonatype/helm3-charts/blob/master/nexus-repository-manager/templates/NOTES.txt#L3) use **.Values.ingress.hosts** to build urls but that value **appears to be empty**.

So your release notes ends with:
`...
1. Get the application URL by running these commands:
`

**Comment by CMYanko** [comment]
thanks, let me look into this

**Comment by jflinchbaugh** [comment]
this has been corrected. https://github.com/sonatype/helm3-charts/pull/152/files#diff-571f805423afdba444dd0d8bf6f72349152d290d14ccab38a40b00d9ff0a56b8
