### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by prasantk** [sonatype/helm3-charts#23]
The annotations field indentation appears to be incorrect here:
https://github.com/sonatype/helm3-charts/blob/1c0a876e54eddf84e800d249ba4f86ecafe04dd8/nexus-iq/templates/persistentVolumeClaim.yaml#L13

While installing the nexus iq chart with annotations enabled for pvc, it throws an error:
error validating "": error validating data: ValidationError(PersistentVolumeClaim): unknown field "annotations" in io.k8s.api.core.v1.PersistentVolumeClaim

A quick glimpse at the api -  _kubectl explain PersistentVolumeClaim.metadata | less_ suggests that the annotations field should come under metadata resource at the same level as name and labels. The following seems to fix the issue for me.

```
metadata:
  name: {{ template "iqserver.fullname" . }}-data
  ...
  annotations:
  {{ toYaml .Values.persistence.annotations | indent 2 }}
  ...
```

**Comment by CMYanko** [comment]
fixed
