### ISSUE TITLE
Automatic license configuration is not working

### ISSUE THREAD

**Issue by prasantk** [sonatype/helm3-charts#24]
The licenseFile seems to be in the wrong place here:
https://github.com/sonatype/helm3-charts/blob/1c0a876e54eddf84e800d249ba4f86ecafe04dd8/nexus-iq/values.yaml#L20

When placed under configYaml resource the same, I was able to install the license automatically:
https://github.com/sonatype/helm3-charts/blob/master/nexus-iq/values.yaml#L105

**Comment by jflinchbaugh** [comment]
this now works as advertised in the values.yaml.
