### ISSUE TITLE
in NOTES.txt at $.Valuies.ingress.hostRepo.host can't evaluate field host

### ISSUE THREAD

**Issue by ruckc** [sonatype/helm3-charts#32]
With 23.1.5 this evening, I get this:

  Error: Failed to render chart: exit status 1: Error: template: nexus-repository-manager/templates/NOTES.txt:3:52: executing "nexus-repository-manager/templates/NOTES.txt" at <$.Values.ingress.hostRepo.host>: can't evaluate field host in type interface {}
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error

**Comment by zacheryph** [comment]
+1 i get the same.  What is the point of this `NOTES.txt` in the templates?

**Comment by CMYanko** [comment]
I feel like a PR for this went through recently??

**Comment by zacheryph** [comment]
This appears to be fixed in master, but is broken in the latest chart release.

**Comment by CMYanko** [comment]
new charts are out now
