### ISSUE TITLE
Can not upgrade with rancher, as latest version seems to be 29.1.0, which is not available

### ISSUE THREAD

**Issue by alexis-morillo** [sonatype/helm3-charts#39]
When upgrading with rancher, using catalog https://sonatype.github.io/helm3-charts/, there is a 404 http response on this url https://github.com/sonatype/helm3-charts/releases/download/nexus-repository-manager-29.1.0/nexus-repository-manager-29.1.0.tgz.
This blocks any upgrade with rancher, as rancher seems to need the latest version available before going any further.

**Comment by amorillotraxens** [comment]
I saw a PR on this, but when will it be approved ? It still blocks us for any upgrade or install via Rancher.

**Comment by jflinchbaugh** [comment]
Latest Nexus Repository Manager should be available now.
