### ISSUE TITLE
Default install for nexus-repository-manager not working

### ISSUE THREAD

**Issue by ranuwp** [sonatype/helm3-charts#43]
I try to do simple install on README.md but it is not working for default version, but when I use version 29.0.0 it is working. It affect when i use chart on Rancher Anyone know how to solve it?

<img width="1438" alt="Screenshot at Dec 17 10-08-05" src="https://user-images.githubusercontent.com/16378086/102438913-ccf2f280-404f-11eb-9675-3b707c750c7d.png">

**Comment by jflinchbaugh** [comment]
Latest versions of Nexus Repository Manager should now be available.
