### ISSUE TITLE
[nexus-repository-manager] Bug in imagePullSecret 

### ISSUE THREAD

**Issue by Hokwang** [sonatype/helm3-charts#44]
Hi,

there's `imagePullSecrets`  https://github.com/sonatype/helm3-charts/blob/4e3d34655d7e17bfa0d95ead956063550a47cf1d/charts/nexus-repository-manager/values.yaml#L70

But in template,
used `nexus.imagePullSecret`,
https://github.com/sonatype/helm3-charts/blob/4e3d34655d7e17bfa0d95ead956063550a47cf1d/charts/nexus-repository-manager/templates/deployment.yaml#L51-L54

and please remove image-pull-secret.yaml file, you don't need to create secret for user.

Most of usecase, I think below syntax.

```
imagePullSecrets:
  - name: secret-name
```

**Comment by Hokwang** [comment]
@CMYanko Can you take care of this issue?

**Comment by jflinchbaugh** [comment]
Thanks. We'll look into fixing this in the near future. We'll report back here to close the issue when it's done. https://issues.sonatype.org/browse/INT-4361

**Comment by kellyrob99** [comment]
@Hokwang we've made the requested changes, hopefully this helps you out!
