### ISSUE TITLE
[nexus-repository-manager] Wrong default value in README.md

### ISSUE THREAD

**Issue by TGuimbert** [sonatype/helm3-charts#46]
The default value of `nexus.docker.enabled` is discibed as `True` in the doc, but is `False` in the `values.yaml`.

A correction should be made in the doc, or in the `values.yaml`.

I can work on the PR, just tell me which one to modify.

**Comment by jflinchbaugh** [comment]
thank you. correcting. https://github.com/sonatype/helm3-charts/pull/91/files
