### ISSUE TITLE
Unable to set custom ingress host

### ISSUE THREAD

**Issue by alec-pinson** [sonatype/helm3-charts#5]
Are these 2 lines correct?

https://github.com/sonatype/helm3-charts/blob/master/nexus-iq/templates/ingress.yaml#L31
https://github.com/sonatype/helm3-charts/blob/master/nexus-iq/templates/ingress.yaml#L38

**Comment by CMYanko** [comment]
Good timing, this is on my list for today!

**Comment by CMYanko** [comment]
As I review it, I had struggled with the toYML rendering. I need to refactor the values and will update

**Comment by CMYanko** [comment]
Fix is up, I'll update the docs after lunch
