### ISSUE TITLE
[nexus-repository-manager] Bug in NOTES.txt

### ISSUE THREAD

**Issue by ramazanaslan82** [sonatype/helm3-charts#55]
`{{ . }}` texts exists in templates/NOTES.txt file.
`1. Get the application URL by running these commands:
{{- if .Values.ingress.enabled }}
  http{{ if $.Values.ingress.tls }}s{{ end }}://{{ $.Values.ingress.hostRepo }}{{ . }}
  `

It causes printing toString() output of spec yaml on deployments...
`[...id.commap[Capabilities:0xc0004cbb90 Chart:0xc00095c480 Files:map[.helmignore:[35 32 80 97 116 116 101 114 110 115 32 116 111 32 105 103 110 111 114 101 32 119 104 101 110 32 98 117 105 108 100 105 110 103 32 112 97 99 107 97 103 101 115 46 10 35...]
`

**Comment by awalker125** [comment]
I get this as well with ingress enabled.

**Comment by jflinchbaugh** [comment]
Latest release should have this corrected now.
