### ISSUE TITLE
[nexus-repository-manager] Have a way to override hardcoded number of replicas (Deployment)

### ISSUE THREAD

**Issue by mpailloncy** [sonatype/helm3-charts#57]
Currently the number of replicas is [hardcoded](https://github.com/sonatype/helm3-charts/blob/master/charts/nexus-repository-manager/templates/deployment.yaml#L17) to 1.

Is there any reason why we can't override it?

**Comment by mpailloncy** [comment]
Apparently that was possible before (see [this commit](https://github.com/sonatype/helm3-charts/commit/73c96b037d6db909e9d63e941e363116a314b154)), but not sure to understand why we can't do it anymore.

cc @CMYanko

**Comment by jglick** [comment]
Presumably you would also need to override https://github.com/sonatype/helm3-charts/blob/ff3eb12b2fc4d8b99dede287b1700f8ce618b237/charts/nexus-repository-manager/values.yaml#L144

**Comment by mpailloncy** [comment]
Yes, my understanding is that we would need to [disable](https://github.com/sonatype/helm3-charts/blob/ff3eb12b2fc4d8b99dede287b1700f8ce618b237/charts/nexus-repository-manager/values.yaml#L143) persistence storage if we configure blob storage to S3/GCS/whatever.

See https://github.com/sonatype/helm3-charts/blob/master/charts/nexus-repository-manager/README.md#persistence

**Comment by jflinchbaugh** [comment]
Having more than one replica sharing resources doesn't make sense for this server right now. This chart is not for high-availability configurations.
