### ISSUE TITLE
Error with HTTPS : Mixed Content: The page at  was loaded over HTTPS, but requested an insecure stylesheet  

### ISSUE THREAD

**Issue by dhawaldenny** [sonatype/helm3-charts#64]
![image](https://user-images.githubusercontent.com/17321299/110382313-bd001300-8080-11eb-987c-6e761d4bbf37.png)

Mixed Content: The page at  was loaded over HTTPS, but requested an insecure stylesheet  
This request has been blocked; the content must be served over HTTPS.

**Comment by gnandiga** [comment]
Any updates on this issue. 

I tried to even update the ingress with https://github.com/kubernetes/ingress-nginx/issues/3192#issuecomment-483281931, but that didn't resolve this issue.

**Comment by ruckc** [comment]
What is the url of the insecure stylesheet from the network tab?  We are running nexus-repository-manager without this issue.

**Comment by gnandiga** [comment]
<img width="1619" alt="Screen Shot 2021-05-28 at 2 08 14 PM" src="https://user-images.githubusercontent.com/34258/120042477-00eb2000-bfbf-11eb-855f-f9ae8ec93502.png">
A lot of urls on the page this issue. 

We have an ingress with AWS NLB, that has certificate attached to the NLB. 

So we just have the nginx controller which is forwarding the requests to nexus pod. Hence I had to setup to forward the headers if there is some X-Forward going on. 

But, if you have any pointers let me know, I will try to give it a try.

**Comment by ruckc** [comment]
our cluster is using ingress-nginx for our controller with cert-manager/letsencrypt certificates.  We are planning to move to ALB with Amazon certs soon, i'll see if I can't repeat your issue.

**Comment by jflinchbaugh** [comment]
all resources loaded from the index page are now relative to the page, so https should follow for all of them, so this was not reproducible.
