### ISSUE TITLE
How to use a local persistent volume claim?

### ISSUE THREAD

**Issue by CodingSpiderFox** [sonatype/helm3-charts#67]
The sample values.yml only contains a pdName variable, I think this is for Google Cloud, right?

How would I use a local volume claim?

**Comment by CodingSpiderFox** [comment]
Thx :)

**Comment by tculp** [comment]
This repo also allows you to specify a `persistence.existingClaim`: https://github.com/sonatype/helm3-charts/blob/de60f09ba4bf4428fc98e6306ba6444c67c12a7a/charts/nexus-repository-manager/values.yaml#L146

**Comment by gbonnefille** [comment]
An update of the README would certainly help future users to quickly discover this feature.

**Comment by jflinchbaugh** [comment]
I'll have the docs fixed shortly.
