### ISSUE TITLE
Typo in values.yaml

### ISSUE THREAD

**Issue by YunSangJun** [sonatype/helm3-charts#69]
-I suppose that "serviceType" should be changed to "type".

https://github.com/sonatype/helm3-charts/blob/master/charts/nexus-repository-manager/values.yaml
```
...
service:
  ...
  serviceType: ClusterIP
```

https://github.com/sonatype/helm3-charts/blob/master/charts/nexus-repository-manager/templates/service.yaml#L19
```
...
spec:
  type: {{ .Values.service.type }}
```

**Comment by jflinchbaugh** [comment]
this has been corrected.
