### ISSUE TITLE
Unable to execute HTTP request: Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by idonca** [sonatype/helm3-charts#70]
Hello team,

We are running OSS Nexus Sonatype on helm kubernetes and, from time to time, we are receiving the following error: `Unable to execute HTTP request: Timeout waiting for connection from pool` 
And we only need to restart the pod.

Could you, please, tell us what can be the problem here?
[nexsus-logs.txt](https://github.com/sonatype/helm3-charts/files/6295889/nexsus-logs.txt)

Attached you can find all the logs. We also increased the Java memory for the process, but no luck.

Thank you,
-Ionut

**Comment by ruckc** [comment]
According to (google)[https://support.sonatype.com/hc/en-us/articles/360055417693-S3-Blobstore-Timeout-waiting-for-connection-from-pool-], a property needs to be set in nexus.properties to increase the thread pool size for the s3 connection pool.

```
nexus.s3.connection.pool=200
```

Though i have no idea how to do this through the helm chart.

**Comment by idonca** [comment]
Hello @ruckc 

I also saw that post. I did add the property in that file. Basically, I did that manually: ssh into the pod and add at the end of the file `/nexus-data/etc/nexus.properties` that property.

I will monitor the behaviour and the logs for a couple of days and after that, I will come back with feedback.

Thank you.
-Ionut

**Comment by ruckc** [comment]
It looks like you can set nexus properties in helm with the nexus.properties.data key:

```yaml
nexus:
  properties:
    override: false
    data:
      nexus.s3.connection.pool=200
```

**Comment by idonca** [comment]
Thanks @ruckc 

We added that property and till now we are not receiving anymore the timeout.
Closing this issue!
