### ISSUE TITLE
Provide option to use non-beta API, some beta APIs are now deprecated

### ISSUE THREAD

**Issue by dmilet** [sonatype/helm3-charts#74]
Eventually, kubernetes 1.22 will come and those beta APIs will be removed
$  helm install nexus -f nexus-values.yaml  sonatype/nexus-repository-manager --namespace nexus-project
W0501 22:30:31.490411    5728 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by jeroenlandheer** [comment]
I'm hitting this issue now, (we already upgraded to 1.22). I'll post a PR for this.

**Comment by dromaniuk** [comment]
Hi. I'm already have the issue. I can't deploy Nexus to my Kubernetes cluster v1.22
Any updates?

**Comment by jflinchbaugh** [comment]
the charts have been updated for k8s 1.22+.
