### ISSUE TITLE
[nexus-repository-manager] Add support for Prometheus metrics

### ISSUE THREAD

**Issue by snakebyte91** [sonatype/helm3-charts#99]
Please add support for prometheus metrics

**Comment by enrico2828** [comment]
Though not natively supported by the chart, I managed to add the jmx exporter with the options currently available: 

Add to values.yml

`
nexus:
  env:
    - name: INSTALL4J_ADD_VM_PARAMS
      value: "-javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent.jar=8082:/usr/share/jmx-exporter-config/config.yaml -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
  docker:
    enabled: true
    registries:
      - port: 8082
        host: dummy-registry-for-jmx-exporter
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
deployment:
  initContainers:
    - name: jmx-exporter-downloader
      image: curlimages/curl:7.80.0
      args:
        - "-o"
        - "/usr/share/jmx-exporter/jmx_prometheus_javaagent.jar"
        - "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar"
      volumeMounts:
        - name: jmx-exporter 
          mountPath: /usr/share/jmx-exporter
  additionalVolumes:
    - name: jmx-exporter
      emptyDir: {}
    - name: jmx-config
      configMap:
        name: jmx-config
  additionalVolumeMounts:
    - name: jmx-exporter 
      mountPath: /usr/share/jmx-exporter
    - name: jmx-config
      mountPath: /usr/share/jmx-exporter-config
`

Add also a configmap:
`
apiVersion: v1
data:
  config.yaml: |
    ---
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    whitelistObjectNames: ["jvm*:*"]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jmx-config
`

If appreciated by the maintainers of this project, I am also willing to work on a MR to officially add an option to the chart. Just let me know.

**Comment by calumgilchristmodulr** [comment]
Nexus natively exports prometheus metrics now at `/service/metrics/prometheus` 

https://help.sonatype.com/repomanager3/nexus-repository-administration/support-features#SupportFeatures-Prometheus

**Comment by joedragons** [comment]
That is true, thanks for the housekeeping note.
